name: run_tests
on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '8'

      - name: Instalar dependencias
        run: composer install

      - name: Ejecutar el linter en carpeta src
        run: php -l src -q

      - name: Ejecutar el linter en carpeta test
        run: php -l test -q

      - name: Ejecutar GrumPHP
        run: ./vendor/bin/grumphp run -c grumphp.yml

      - name: Correr tests con PHPUnit
        run: ./vendor/bin/phpunit -c phpunit.xml